name: mora
description: "A new Flutter application for my brother's shop."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.2
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.3.1
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/lotties/
